<a href="https://colab.research.google.com/github/Pedrolustosa/exercicio_numpy/blob/main/exercicio_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

1 - Utilize o método numpy.info para obter informações do método numpy.add.

In [4]:
# Insira a resposta abaixo.
import numpy as np

np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15.

In [5]:
# Insira a resposta abaixo.
numeros = list(range(16))
print(numeros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


3 - Converta a lista criada para um objeto do tipo numpy array.

In [6]:
# Insira a resposta abaixo.
numeros_array = np.array(numeros)
print(numeros_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [7]:
# Insira a resposta abaixo.
numeros_array = np.arange(10)
print(numeros_array)

[0 1 2 3 4 5 6 7 8 9]


5 - Utilize o array criado anteriormente para exibir o tipo de dado antes e após convertê-lo para um tipo float. Em seguida, converta novamente o array para um tipo de dado inteiro de 32 bits e exiba o tipo numérico  atual.

In [8]:
# Insira a resposta abaixo.
numeros_array = np.arange(16)
print("Tipo de dado original:", numeros_array.dtype)
numeros_array_float = numeros_array.astype(float)
print("Tipo de dado após conversão para float:", numeros_array_float.dtype)
numeros_array_int32 = numeros_array_float.astype(np.int32)
print("Tipo de dado após conversão para inteiro de 32 bits:", numeros_array_int32.dtype)


Tipo de dado original: int64
Tipo de dado após conversão para float: float64
Tipo de dado após conversão para inteiro de 32 bits: int32


6 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [9]:
# Insira a resposta abaixo.
numeros_array = np.arange(16)
numeros_array_int32 = numeros_array.astype(np.int32)
print("Formato atual do array:", numeros_array_int32.shape)
numeros_array_int32 = numeros_array_int32.reshape(4, 4)
print("Formato do array após redimensionamento:", numeros_array_int32.shape)

Formato atual do array: (16,)
Formato do array após redimensionamento: (4, 4)


7 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [10]:
# Insira a resposta abaixo.
numeros_array = np.arange(16, dtype=np.int32)
numeros_array = numeros_array.reshape(4, 4)
media = np.mean(numeros_array)
mediana = np.median(numeros_array)
desvio_padrao = np.std(numeros_array)
print("Array:")
print(numeros_array)
print("\nMédia:", media)
print("Mediana:", mediana)
print("Desvio padrão:", desvio_padrao)


Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Média: 7.5
Mediana: 7.5
Desvio padrão: 4.6097722286464435


8 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [11]:
# Insira a resposta abaixo.
numeros_array = np.arange(16, dtype=np.int32)
numeros_array = numeros_array.reshape(4, 4)
numeros_array_negativo = np.copy(numeros_array)
numeros_array_negativo *= -1
print("Array Original:")
print(numeros_array)
print("\nArray com Números Negativos:")
print(numeros_array_negativo)


Array Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Array com Números Negativos:
[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


9 - Realize os seguintes procedimentos:
1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.
2.  Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo.
3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

In [12]:
# Insira a resposta abaixo.
numeros_array = np.arange(16, dtype=np.int32)
numeros_array = numeros_array.reshape(4, 4)
numeros_array_negativo = -np.copy(numeros_array)
concatenacao_vertical = np.vstack((numeros_array, numeros_array_negativo))
concatenacao_horizontal = np.hstack((concatenacao_vertical, concatenacao_vertical))
concatenacao_profundidade = np.dstack((concatenacao_horizontal, concatenacao_horizontal, concatenacao_horizontal))
print("Formato final do array:")
print(concatenacao_profundidade.shape)

Formato final do array:
(8, 8, 3)


10 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [13]:
# Insira a resposta abaixo.
numeros_array = np.arange(16).reshape(4, 4)
numeros_array_negativo = -np.copy(numeros_array)
concatenacao_vertical = np.vstack((numeros_array, numeros_array_negativo))
concatenacao_vertical[:, 1:3] = 1
print("Array modificado:")
print(concatenacao_vertical)


Array modificado:
[[  0   1   1   3]
 [  4   1   1   7]
 [  8   1   1  11]
 [ 12   1   1  15]
 [  0   1   1  -3]
 [ -4   1   1  -7]
 [ -8   1   1 -11]
 [-12   1   1 -15]]


11 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [15]:
# Insira a resposta abaixo.
array_modificado = np.array([
    [  0,   1,   1,   3],
    [  4,   1,   1,   7],
    [  8,   1,   1,  11],
    [ 12,   1,   1,  15],
    [  0,  -1,  -1,  -3],
    [ -4,  -1,  -1,  -7],
    [ -8,  -1,  -1, -11],
    [-12,  -1,  -1, -15]
], dtype=np.float64)

array_modificado += 2.5
print("Array após adicionar 2.5:")
print(array_modificado)

Array após adicionar 2.5:
[[  2.5   3.5   3.5   5.5]
 [  6.5   3.5   3.5   9.5]
 [ 10.5   3.5   3.5  13.5]
 [ 14.5   3.5   3.5  17.5]
 [  2.5   1.5   1.5  -0.5]
 [ -1.5   1.5   1.5  -4.5]
 [ -5.5   1.5   1.5  -8.5]
 [ -9.5   1.5   1.5 -12.5]]


12 - Apresente uma contagem dos valores únicos que estão presentes no array criado na questão anterior.

 Siga o seguinte template: "Quantidade de ocorrências do elemento {}: {}"

In [16]:
# Insira a resposta abaixo.
array_modificado = np.array([array_modificado], dtype=np.float64)
valores_unicos, contagens = np.unique(array_modificado, return_counts=True)
for valor, contagem in zip(valores_unicos, contagens):
    print("Quantidade de ocorrências do elemento {}: {}".format(valor, contagem))

Quantidade de ocorrências do elemento -12.5: 1
Quantidade de ocorrências do elemento -9.5: 1
Quantidade de ocorrências do elemento -8.5: 1
Quantidade de ocorrências do elemento -5.5: 1
Quantidade de ocorrências do elemento -4.5: 1
Quantidade de ocorrências do elemento -1.5: 1
Quantidade de ocorrências do elemento -0.5: 1
Quantidade de ocorrências do elemento 1.5: 8
Quantidade de ocorrências do elemento 2.5: 2
Quantidade de ocorrências do elemento 3.5: 8
Quantidade de ocorrências do elemento 5.5: 1
Quantidade de ocorrências do elemento 6.5: 1
Quantidade de ocorrências do elemento 9.5: 1
Quantidade de ocorrências do elemento 10.5: 1
Quantidade de ocorrências do elemento 13.5: 1
Quantidade de ocorrências do elemento 14.5: 1
Quantidade de ocorrências do elemento 17.5: 1


13 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [17]:
# Insira a resposta abaixo.
matriz_3 = np.full((4, 2), 3)
matriz_identidade = np.eye(4)
produto = matriz_3.T @ matriz_identidade
print("Resultado do produto:")
print(produto)


Resultado do produto:
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


14 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [18]:
# Insira a resposta abaixo.
matriz_inteiros = np.arange(25, 50).reshape(5, 5)
matriz_uniforme = np.random.rand(5, 1)
concatenacao_horizontal = np.hstack((matriz_inteiros, matriz_uniforme))
print("Matriz de inteiros:")
print(matriz_inteiros)
print("\nMatriz uniforme:")
print(matriz_uniforme)
print("\nResultado da concatenação horizontal:")
print(concatenacao_horizontal)

Matriz de inteiros:
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

Matriz uniforme:
[[0.03259342]
 [0.06646919]
 [0.28851495]
 [0.04417655]
 [0.52037718]]

Resultado da concatenação horizontal:
[[2.50000000e+01 2.60000000e+01 2.70000000e+01 2.80000000e+01
  2.90000000e+01 3.25934216e-02]
 [3.00000000e+01 3.10000000e+01 3.20000000e+01 3.30000000e+01
  3.40000000e+01 6.64691939e-02]
 [3.50000000e+01 3.60000000e+01 3.70000000e+01 3.80000000e+01
  3.90000000e+01 2.88514954e-01]
 [4.00000000e+01 4.10000000e+01 4.20000000e+01 4.30000000e+01
  4.40000000e+01 4.41765495e-02]
 [4.50000000e+01 4.60000000e+01 4.70000000e+01 4.80000000e+01
  4.90000000e+01 5.20377178e-01]]


15 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear.

In [19]:
# Insira a resposta abaixo.
matriz_logaritmica = np.logspace(start=1, stop=2, num=5).reshape(-1, 1)
print("Matriz com espaçamento logarítmico:")
print(matriz_logaritmica)

Matriz com espaçamento logarítmico:
[[ 10.        ]
 [ 17.7827941 ]
 [ 31.6227766 ]
 [ 56.23413252]
 [100.        ]]


16 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado.

In [20]:
# Insira a resposta abaixo.
def adicionar_borda_de_zeros(array):
    pad_width = ((1, 1), (1, 1))
    array_com_borda = np.pad(array, pad_width, mode='constant', constant_values=0)
    return array_com_borda

matriz_logaritmica = np.logspace(start=1, stop=2, num=5).reshape(-1, 1)
matriz_com_borda = adicionar_borda_de_zeros(matriz_logaritmica)
print("Matriz original:")
print(matriz_logaritmica)
print("\nMatriz com borda de zeros:")
print(matriz_com_borda)

Matriz original:
[[ 10.        ]
 [ 17.7827941 ]
 [ 31.6227766 ]
 [ 56.23413252]
 [100.        ]]

Matriz com borda de zeros:
[[  0.           0.           0.        ]
 [  0.          10.           0.        ]
 [  0.          17.7827941    0.        ]
 [  0.          31.6227766    0.        ]
 [  0.          56.23413252   0.        ]
 [  0.         100.           0.        ]
 [  0.           0.           0.        ]]


17 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [21]:
# Insira a resposta abaixo.
np.random.seed(0)
array_normal = np.random.normal(size=36)
print("Array de números aleatórios:")
print(array_normal)
valor_maximo = np.max(array_normal)
valor_minimo = np.min(array_normal)
media = np.mean(array_normal)
desvio_padrao = np.std(array_normal)
print("\nValor máximo:", valor_maximo)
print("Valor mínimo:", valor_minimo)
print("Média:", media)
print("Desvio padrão:", desvio_padrao)

Array de números aleatórios:
[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351
  0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826
  0.3130677  -0.85409574 -2.55298982  0.6536186   0.8644362  -0.74216502
  2.26975462 -1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877
  0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215  0.15634897]

Valor máximo: 2.2697546239876076
Valor mínimo: -2.5529898158340787
Média: 0.29885161019772544
Desvio padrão: 1.0904075497979766
